"""Auto migration

Revision ID: 60ebaabea8a4
Revises: 
Create Date: 2025-12-02 12:33:29.415848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ebaabea8a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_uri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_uri', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('base_uri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_base_uri_base_uri'), ['base_uri'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_uri_id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('creator_username', sa.String(length=255), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('number_of_items', sa.Integer(), nullable=True),
    sa.Column('size_in_bytes', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['base_uri_id'], ['base_uri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_creator_username'), ['creator_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_uri'), ['uri'], unique=True)
        batch_op.create_index(batch_op.f('ix_dataset_uuid'), ['uuid'], unique=False)

    op.create_table('register_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_uri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_uri_id'], ['base_uri.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'base_uri_id')
    )
    op.create_table('search_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_uri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_uri_id'], ['base_uri.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'base_uri_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_permissions')
    op.drop_table('register_permissions')
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_uuid'))
        batch_op.drop_index(batch_op.f('ix_dataset_uri'))
        batch_op.drop_index(batch_op.f('ix_dataset_name'))
        batch_op.drop_index(batch_op.f('ix_dataset_creator_username'))

    op.drop_table('dataset')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('base_uri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_base_uri_base_uri'))

    op.drop_table('base_uri')
    # ### end Alembic commands ###
